### PR TITLE
FH-3853 Use fh-sync-js instead of fh-js-sdk

### PR DESCRIPTION
**Pull request by aidenkeating**
This replaces the current use of fh-js-sdk with fh-sync-js. This
has a few differences:

* fhconfig.json is no longer used, instead config is provided to the library
* The currently used $fh.sync is replaced with the fhSync variable

There is a sample config file titled sync-config.json added to the
root of the project, this is emulating a configuration file that
is provided by the Mobile Control Panel.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@david-martin @maleck13 Would you mind taking a look? I think that's everything we want.

Not sure if that's the kind of structure we're looking for in the `sync-config.json` file?

Tested the app out a bit and it's working. Although there appears to be a few error statements in the console, these occurred before the changes, I'll see if I can resolve them.

**Comment by david-martin** [comment]
@aidenkeating lets hold off on merging this until we figure out where this version of the app should live.
I'm hesitant to have this change make it into RHMAP bundled templates as it could cause confusion with other $fh apis not being available.

**Comment by camilamacedo86** [comment]
Hi @aidenkeating,

If the `fhconfig.json` will be removed how will work the actions in features which use it? Is the disable connection tag working after removing it? Could you perform the following test?

1. Create this project into RHMAP
2. Build it via RHMAP
3. Install into a device
4. Load the app
5. Go to the client app >> connections >> disable the tag and check if it still works because it should stop to work.

Also, is not the information into this file used to count the metrics into the resource feature?

**Comment by aidenkeating** [comment]
Hello @camilamacedo86 

This change isn't intended to be included with RHMAP. That was the reason this was going to be merged to the `mobile.next` branch instead of merging to `master`.

Thinking about the comment made by @david-martin I now think it would be better to move this version of the app to another repo to avoid any further confusion.

**Comment by camilamacedo86** [comment]
Hi @aidenkeating,

I understand that a lot of currently features will still for Mobile.Next for example UPS. The UPS uses the information of this file either. A lot of things into the product requires the information into this file. So, I don't have a full knowledge about the mobile.next, however, shows that this file will be required there either.

**Pull request closed without merging**
