### PR TITLE
RHMAP-13776 Sync Framework project - cannot update items

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Review by pb82 — COMMENTED** [review]
Do we want to lock down all dependencies or just angular for now?

**Review by pb82 — APPROVED** [review]
LGTM, just a comment

**Review by thailekha — COMMENTED** [review]
LGTM

**Review by thailekha — APPROVED** [review]
LGTM

**Comment by jcesarmobile** [comment]
@pb82 on https://issues.jboss.org/browse/RHMAP-13826 John said 
> explicit versions (including patch number) or ~ as the fuzzy matcher should be our default.

I think we should do it for all

**Pull request merged**
